export const selectArray = intl => [
  { value: "", title: "" },
  { value: "libyan", title: intl.formatMessage({ id: "LIBYAN" }) },
  { value: "emirates", title: intl.formatMessage({ id: "EMIRATES" }) },
  { value: "bahraini", title: intl.formatMessage({ id: "BAHRAINI" }) },
  { value: "kuwaiti", title: intl.formatMessage({ id: "KUWAITI" }) },
  {
    value: "saudi arabian",
    title: intl.formatMessage({ id: "SAUDI.ARABIAN" }),
  },
  { value: "omani", title: intl.formatMessage({ id: "OMANI" }) },
  { value: "qatari", title: intl.formatMessage({ id: "QATARI" }) },
  { value: "yemeni", title: intl.formatMessage({ id: "YEMENI" }) },
  { value: "jordanian", title: intl.formatMessage({ id: "JORDANIAN" }) },
  { value: "Syrian", title: intl.formatMessage({ id: "SYRIAN" }) },
  { value: "lebanese", title: intl.formatMessage({ id: "LEBANESE" }) },
  { value: "palestinian", title: intl.formatMessage({ id: "PALESTINIAN" }) },
  { value: "iraqi", title: intl.formatMessage({ id: "IRAQI" }) },
  { value: "egyptian", title: intl.formatMessage({ id: "EGYPTIAN" }) },
  { value: "moroccan", title: intl.formatMessage({ id: "MOROCCAN" }) },
  { value: "tunisian", title: intl.formatMessage({ id: "TUNISIAN" }) },
  { value: "algerian", title: intl.formatMessage({ id: "ALGERIAN" }) },
  { value: "sudanese", title: intl.formatMessage({ id: "SUDANESE" }) },
  { value: "other", title: intl.formatMessage({ id: "OTHER" }) },
]

export const tableTranslation = intl => [
  { libyan: intl.formatMessage({ id: "LIBYAN" }) },
  { emirates: intl.formatMessage({ id: "EMIRATES" }) },
  { bahraini: intl.formatMessage({ id: "BAHRAINI" }) },
  { kuwaiti: intl.formatMessage({ id: "KUWAITI" }) },
  { "saudi arabian": intl.formatMessage({ id: "SAUDI.ARABIAN" }) },
  { omani: intl.formatMessage({ id: "OMANI" }) },
  { qatari: intl.formatMessage({ id: "QATARI" }) },
  { yemeni: intl.formatMessage({ id: "YEMENI" }) },
  { jordanian: intl.formatMessage({ id: "JORDANIAN" }) },
  { syrian: intl.formatMessage({ id: "SYRIAN" }) },
  { lebanese: intl.formatMessage({ id: "LEBANESE" }) },
  { palestinian: intl.formatMessage({ id: "PALESTINIAN" }) },
  { iraqi: intl.formatMessage({ id: "IRAQI" }) },
  { egyptian: intl.formatMessage({ id: "EGYPTIAN" }) },
  { moroccan: intl.formatMessage({ id: "MOROCCAN" }) },
  { tunisian: intl.formatMessage({ id: "TUNISIAN" }) },
  { algerian: intl.formatMessage({ id: "ALGERIAN" }) },
  { sudanese: intl.formatMessage({ id: "SUDANESE" }) },
  { other: intl.formatMessage({ id: "OTHER" }) },
]
