const carouselTypes = {
  GET_CAROUSEL_IMAGES_START: "GET_CAROUSEL_IMAGES_START",
  GET_CAROUSEL_IMAGES_SUCCESS: "GET_CAROUSEL_IMAGES_SUCCESS",
  GET_CAROUSEL_IMAGES_FAILURE: "GET_CAROUSEL_IMAGES_FAILURE",
  ADD_IMAGE_TO_CAROUSEL_START: "ADD_IMAGE_TO_CAROUSEL_START",
  ADD_IMAGE_TO_CAROUSEL_SUCCESS: "ADD_IMAGE_TO_CAROUSEL_SUCCESS",
  ADD_IMAGE_TO_CAROUSEL_FAILURE: "ADD_IMAGE_TO_CAROUSEL_FAILURE",
  DELETE_IMAGE_FROM_CAROUSEL_START: "DELETE_IMAGE_FROM_CAROUSEL_START",
  DELETE_IMAGE_FROM_CAROUSEL_SUCCESS: "DELETE_IMAGE_FROM_CAROUSEL_SUCCESS",
  DELETE_IMAGE_FROM_CAROUSEL_FAILURE: "DELETE_IMAGE_FROM_CAROUSEL_FAILURE",
  CLEAR_ADD_IMAGE_TO_CAROUSEL_ERROR_MESSAGE:
    "CLEAR_ADD_IMAGE_TO_CAROUSEL_ERROR_MESSAGE",
  CLEAR_DELETE_IMAGE_FROM_CAROUSEL_ERROR_MESSAGE:
    "CLEAR_DELETE_IMAGE_FROM_CAROUSEL_ERROR_MESSAGE",
  CLEAR_IMAGES: "CLEAR_IMAGES",
}

export default carouselTypes
