import {
  User,
  Mail,
  MessageCircle,
  FileText,
  Edit,
  Trello,
  Book,
  Folder,
  Database,
  Calendar,
  Clipboard,
} from "react-feather"

export default [
  {
    header: "Pages",
  },
  {
    id: "dashboard",
    title: "dashboard",
    icon: <Trello size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "dashboard",
    navLink: "/dashboard",
  },
  {
    id: "users",
    title: "users",
    icon: <User size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "users",
    navLink: "/users",
  },
  {
    id: "contact",
    title: "contact",
    icon: <Mail size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "contact",
    navLink: "/contact",
  },
  {
    id: "chat",
    title: "chat",
    icon: <MessageCircle size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "chat-nav",
    navLink: "/chat",
  },
  {
    id: "announcements",
    title: "announcements",
    icon: <FileText size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "announcements-nav",
    navLink: "/announcements",
  },
  {
    id: "followups",
    title: "follow ups",
    icon: <Edit size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "followups-nav",
    navLink: "/followups",
  },
  {
    id: "consultation",
    title: "consultation",
    icon: <Calendar size={20} />,
    badge: "primary",
    badgeText: "1",
    action: "read",
    resource: "consultation",
    navLink: "/consultation",
  },
  {
    id: "files",
    title: "files",
    icon: <Folder size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "files",
    navLink: "/files",
  },
  {
    id: "management",
    title: "management",
    icon: <Database size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "management",
    navLink: "/management",
  },
  {
    id: "subjects",
    title: "subjects",
    icon: <Book size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "lecturerSubjects-nav",
    navLink: "/lecturerSubjects",
  },
  {
    id: "weeklyTimetable",
    title: "weekly timetable",
    icon: <Clipboard size={20} />,
    badge: "light-warning",
    action: "read",
    resource: "lecturerTimetable-nav",
    navLink: "/lecturerTimetable",
  },
]
